### ISSUE TITLE
Error after upgrading to 4.4.1: Minio.put_object() got an unexpected keyword argument 'headers'

### ISSUE THREAD

**Issue by Sebastien-M** [theriverman/django-minio-backend#69]
After upgrading to 4.4.1 and trying to add an object the following error occurs:

```
web-1  | Traceback (most recent call last):
web-1  |   File "/usr/local/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
web-1  |     response = get_response(request)
web-1  |   File "/usr/local/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
web-1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web-1  |   File "/usr/local/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
web-1  |     return view_func(request, *args, **kwargs)
web-1  |   File "/usr/local/lib/python3.13/site-packages/django/views/generic/base.py", line 105, in view
web-1  |     return self.dispatch(request, *args, **kwargs)
web-1  |            ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/usr/local/lib/python3.13/site-packages/rest_framework/views.py", line 515, in dispatch
web-1  |     response = self.handle_exception(exc)
web-1  |   File "/usr/local/lib/python3.13/site-packages/rest_framework/views.py", line 475, in handle_exception
web-1  |     self.raise_uncaught_exception(exc)
web-1  |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
web-1  |   File "/usr/local/lib/python3.13/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
web-1  |     raise exc
web-1  |   File "/usr/local/lib/python3.13/site-packages/rest_framework/views.py", line 512, in dispatch
web-1  |     response = handler(request, *args, **kwargs)
web-1  |   File "/usr/local/lib/python3.13/site-packages/rest_framework/generics.py", line 259, in put
web-1  |     return self.update(request, *args, **kwargs)
web-1  |            ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/usr/local/lib/python3.13/site-packages/rest_framework/mixins.py", line 68, in update
web-1  |     self.perform_update(serializer)
web-1  |     ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
web-1  |   File "/usr/local/lib/python3.13/site-packages/rest_framework/mixins.py", line 78, in perform_update
web-1  |     serializer.save()
web-1  |     ~~~~~~~~~~~~~~~^^
web-1  |   File "/usr/local/lib/python3.13/site-packages/rest_framework/serializers.py", line 205, in save
web-1  |     self.instance = self.update(self.instance, validated_data)
web-1  |                     ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/app/app/serializers/custom_user.py", line 119, in update
web-1  |     return super().update(instance, validated_data)
web-1  |            ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/usr/local/lib/python3.13/site-packages/rest_framework/serializers.py", line 1035, in update
web-1  |     instance.save()
web-1  |     ~~~~~~~~~~~~~^^
web-1  |   File "/usr/local/lib/python3.13/site-packages/django/contrib/auth/base_user.py", line 65, in save
web-1  |     super().save(*args, **kwargs)
web-1  |     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
web-1  |   File "/usr/local/lib/python3.13/site-packages/django/db/models/base.py", line 902, in save
web-1  |     self.save_base(
web-1  |     ~~~~~~~~~~~~~~^
web-1  |         using=using,
web-1  |         ^^^^^^^^^^^^
web-1  |     ...<2 lines>...
web-1  |         update_fields=update_fields,
web-1  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |     )
web-1  |     ^
web-1  |   File "/usr/local/lib/python3.13/site-packages/django/db/models/base.py", line 1008, in save_base
web-1  |     updated = self._save_table(
web-1  |         raw,
web-1  |     ...<4 lines>...
web-1  |         update_fields,
web-1  |     )
web-1  |   File "/usr/local/lib/python3.13/site-packages/django/db/models/base.py", line 1132, in _save_table
web-1  |     (getattr(self, f.attname) if raw else f.pre_save(self, False)),
web-1  |                                           ~~~~~~~~~~^^^^^^^^^^^^^
web-1  |   File "/usr/local/lib/python3.13/site-packages/django/db/models/fields/files.py", line 338, in pre_save
web-1  |     file.save(file.name, file.file, save=False)
web-1  |     ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/usr/local/lib/python3.13/site-packages/django_resized/forms.py", line 125, in save
web-1  |     super(ResizedImageFieldFile, self).save(name, new_content, save)
web-1  |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/usr/local/lib/python3.13/site-packages/django/db/models/fields/files.py", line 99, in save
web-1  |     self.name = self.storage.save(name, content, max_length=self.field.max_length)
web-1  |                 ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/usr/local/lib/python3.13/site-packages/django/core/files/storage/base.py", line 49, in save
web-1  |     name = self._save(name, content)
web-1  |   File "/usr/local/lib/python3.13/site-packages/django_minio_backend/models.py", line 215, in _save
web-1  |     self.client.put_object(
web-1  |     ~~~~~~~~~~~~~~~~~~~~~~^
web-1  |         bucket_name=self.bucket,
web-1  |         ^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |     ...<16 lines>...
web-1  |         extra_query_params=self._META_KWARGS.get('extra_query_params', None),
web-1  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |     )
web-1  |     ^
web-1  | TypeError: Minio.put_object() got an unexpected keyword argument 'headers'
```

The issue seems to be linked to the changes made inside 4.4.1 https://github.com/theriverman/django-minio-backend/commit/ddaf36836f7a7634aa7335b3fc228afac6c4bd2b

**Comment by theriverman** [comment]
The minio-python SDK has done some changes recently which are rather confusing to me from a semantic versioning perspective introducing breaking changes in patch releases.

I've pinned minio=7.2.19 in 097d085386ed34dc6a4f4e8508fe2ad62e3506eb.

Thanks for the feedback!
